import { useContext, FormEvent, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Router from 'next/router'

import { Input } from '../../components/ui/Input'
import { Button } from '../../components/ui/Button'

import { AuthContext } from '../../contexts/AuthContext'
import { canSSRGuest } from '../../utils/canSSRGuest'

import logo from '../../../public/img/logo.png'
import bgLogin from '../../../public/img/pizzas.webp'

export default function Login(){
	const { signIn } = useContext(AuthContext)

	const [email, setEmail] = useState<string>("")
	const [password, setPassword] = useState<string>("")
	const [loading, setLoading] = useState<boolean>(false)

	async function handleSubmit(e: FormEvent) {
		setLoading(true)
		e.preventDefault();
		let data = {
			email,
			password
		}
		await signIn(data)
		setLoading(false)
	}

	return(
		<div>
			<Head>
				<title>LogIn - BarDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="w-full h-[100vh] flex tablet-min:flex-col">
					<div className="w-[50%] tablet-min:w-full">
						<img src="/img/pizzas.webp" className="w-full h-full object-cover" alt="" />
					</div>
					<div className="flex flex-col justify-center items-center relative w-[50%] tablet-min:w-full">
						<Image src={logo} width={180} height={180} alt=""/>
						<div className="w-[60%] flex flex-col gap-1 tablet-min:w-[80%]">
							<h1 className="text-4xl font-semibold text-gray-50 desktop:text-2xl">Portal da Comida</h1>
							<span className="text-base font-normal text-gray-50">A melhor comida da cidade</span>
						</div>
						<form className="flex flex-col w-[60%] mt-5 tablet-min:w-[80%]" onSubmit={handleSubmit}>
							<label>E-mail</label>
							<Input type="email" placeholder="nome@nome.com" width={"w-full"} value={email} onChange={(e) => setEmail(e.target.value)} />
							<label>Senha</label>
							<Input type="password" placeholder="Sua senha" width={"w-full"} value={password} onChange={(e) => setPassword(e.target.value)} />
							<Button type="submit" tailwindCss="bg-yellow-700" loading={loading} >Logar</Button>
						</form>
					</div>
				</div>
			</main>
		</div>
	)
}

export const getServerSideProps = canSSRGuest( async (context) => {
	return {
		props: {}
	}
})
