import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { canSSRAuth } from '../utils/canSSRAuth'

import ButtonUI from '@mui/material/Button';
import { Header } from '../components/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pizzaria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
				<Header />
			</main>
    </>
  )
}

export const getServerSideProps = canSSRAuth(async () => {
		return {
			props: {}
		}
})
